server:
  port: 9191
  servlet:
    context-path: /api
spring:
  h2:
    console:
      path: /h2
      enabled: true
  datasource:
    url: jdbc:h2:mem:seamhealth
    driverClassName: org.h2.Driver
    password: 1234
    username: admin

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

#server.port=9191
#spring.datasource.url=jdbc:postgresql://localhost:5433/school_dbo
#spring.datasource.password=12345
#server.servlet.context-path=/api
#spring.datasource.username=postgres
#spring.datasource.driver-class-name= org.postgresql.Driver
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL9Dialect
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.generate-ddl=true
